version: "3"
services:

  api:
    build: ./api
    ports:
    - "5000:5000"
    volumes:
      - ./uploads:/api/public/uploads

  client:
    build: ./client
    ports:
    - "3000:3000"
    depends_on: 
    - api


